# Generated by Django 2.0.4 on 2018-04-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogspot', '0002_remove_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='sub_Heading',
            new_name='sub_heading',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='sub_Title',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tags',
            new_name='title',
        ),
    ]
