# Generated by Django 2.0.4 on 2018-04-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogspot', '0003_auto_20180425_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='banner_Photo',
            new_name='banner_photo',
        ),
    ]
