# Generated by Django 2.0.4 on 2018-04-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogspot', '0006_auto_20180427_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
